import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/navbar";
import LoadingProgressBar from "@/component/common/LoadingProgressBar";
import { UserContextProvider } from "./userContext";
import { ToastProvider } from "@/component/notify/notify";
import { OscarProvider } from "@/component/oscar/oscar-context/oscar-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Malek Daily Assistant",
  description: "Generated by create next app",
  icons: {
    icon: "/img/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <LoadingProgressBar />
        <Navbar />
        <UserContextProvider>
          <ToastProvider>
            <OscarProvider>{children}</OscarProvider>
          </ToastProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
